name: edgex
services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      edgex-network: null
    user: "2002:2001"
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    networks:
      edgex-network: null
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=myuser
      - DOCKER_INFLUXDB_INIT_PASSWORD=mypassword
      - DOCKER_INFLUXDB_INIT_ORG=myorg
      - DOCKER_INFLUXDB_INIT_BUCKET=Mqtt
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=mytoken
  telegraf:
    image: telegraf:latest
    container_name: telegraf
    networks:
      edgex-network: null
    depends_on:
      - mosquitto
      - influxdb
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    networks:
      edgex-network: null
    depends_on:
      - influxdb
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
networks:
  edgex-network:
    name: edgex_edgex-network
    driver: bridge
volumes:
  influxdb-data:
  grafana-data:
  mosquitto_data:
  mosquitto_log:
